# Generated by Django 5.2.9 on 2025-12-14 15:49

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Email address used for login', max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, help_text='Full name of the user', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='International phone number format', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format. Example: +233241234567', regex='^\\+?1?\\d{9,15}$')])),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture - Max 5MB, JPG/PNG/WebP', null=True, upload_to='profiles/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the user', max_length=500)),
                ('city', models.CharField(blank=True, help_text='City of residence', max_length=100)),
                ('country', models.CharField(blank=True, default='Ghana', help_text='Country of residence', max_length=100)),
                ('is_profile_completed', models.BooleanField(default=False, help_text='Indicates if user completed profile setup')),
                ('username_last_changed', models.DateTimeField(blank=True, help_text='Last time username was changed', null=True)),
                ('marketing_emails', models.BooleanField(default=True, help_text='Receive marketing and promotional emails')),
                ('event_reminders', models.BooleanField(default=True, help_text='Receive reminders about upcoming events')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when user registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of last profile update')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProfile',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], help_text='Payment method type', max_length=20)),
                ('name', models.CharField(help_text='Friendly name for this payment profile', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of this payment profile', max_length=500)),
                ('account_details', models.JSONField(help_text='Account details (mobile number, account number, etc.)')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=1.5, help_text='Transaction fee percentage for this payment method', max_digits=4)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('verification_failed', 'Verification Failed')], default='pending_verification', help_text='Verification status', max_length=25)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this payment profile has been verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the payment profile was verified', null=True)),
                ('verification_initiated_at', models.DateTimeField(blank=True, help_text='When verification was initiated', null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts')),
                ('last_verification_attempt', models.DateTimeField(blank=True, help_text='Last verification attempt time', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for verification failure', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this payment profile', on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Profile',
                'verbose_name_plural': 'Payment Profiles',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='idx_user_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='paymentprofile',
            index=models.Index(fields=['user'], name='idx_payment_profile_user'),
        ),
        migrations.AddIndex(
            model_name='paymentprofile',
            index=models.Index(fields=['status'], name='idx_payment_profile_status'),
        ),
        migrations.AddIndex(
            model_name='paymentprofile',
            index=models.Index(fields=['is_verified'], name='idx_payment_profile_verified'),
        ),
    ]
