# Generated by Django 5.2.9 on 2026-01-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Indicates if user has created at least one event (for verification purposes)'),
        ),
    ]
