# Generated by Django 5.2.9 on 2026-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Government-issued ID document', null=True, upload_to='verification/ids/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_image',
            field=models.ImageField(blank=True, help_text='Selfie for identity verification', null=True, upload_to='verification/selfies/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification (rejection reason, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('id_uploaded', 'ID Uploaded'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', help_text='Current verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When verification was submitted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When user was verified as organizer', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Verified organizer status - enabled after ID verification'),
        ),
    ]
