# Generated by Django 5.2.9 on 2026-01-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_id_document_user_selfie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack transfer recipient code', max_length=255),
        ),
    ]
