# Generated by Django 5.2.9 on 2026-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentprofile_paystack_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprofile',
            name='verification_charge_reference',
            field=models.CharField(blank=True, help_text='Paystack charge reference for GHS 1 verification', max_length=255),
        ),
    ]
