# Generated by Django 5.1.4 on 2026-01-21 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paymentprofile_verification_charge_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReengagementEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the email was sent')),
                ('user', models.ForeignKey(help_text='User who received the re-engagement email', on_delete=django.db.models.deletion.CASCADE, related_name='reengagement_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Re-engagement Email',
                'verbose_name_plural': 'User Re-engagement Emails',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user'], name='idx_reengagement_user'), models.Index(fields=['sent_at'], name='idx_reengagement_sent')],
            },
        ),
    ]
