# Generated by Django 5.2.9 on 2025-12-14 12:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text='Icon name/class for the category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is category active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed event description')),
                ('short_description', models.CharField(blank=True, help_text='Short description for previews', max_length=500)),
                ('banner_image', models.ImageField(help_text='Event banner image', upload_to='events/banners/%Y/%m/')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Event thumbnail image', null=True, upload_to='events/thumbnails/%Y/%m/')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', help_text='Event status', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Event privacy setting', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show event in featured section')),
                ('is_free', models.BooleanField(default=False, help_text='Is this a free event')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (null = unlimited)', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the event', max_length=500)),
                ('external_url', models.URLField(blank=True, help_text='External event URL (if applicable)')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Event-specific terms and conditions')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of times event was viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(help_text='Event organizer', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Event category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.eventcategory')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, help_text='Unique order identifier', max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Order status', max_length=20)),
                ('buyer_email', models.EmailField(help_text="Buyer's email address", max_length=254)),
                ('buyer_phone', models.CharField(blank=True, help_text="Buyer's phone number", max_length=20)),
                ('buyer_name', models.CharField(help_text="Buyer's full name", max_length=255)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='External payment reference', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was completed', null=True)),
                ('event', models.ForeignKey(help_text='Event for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.event')),
                ('user', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, help_text='Unique payment identifier', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('flutterwave', 'Flutterwave'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], help_text='Payment gateway used', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, help_text='Gateway transaction reference', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full gateway response data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the payer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('order', models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ticket type name (e.g., VIP, Regular)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Ticket type description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(help_text='Total number of tickets available')),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number of tickets sold')),
                ('min_purchase', models.PositiveIntegerField(default=1, help_text='Minimum tickets per purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_purchase', models.PositiveIntegerField(default=10, help_text='Maximum tickets per purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('sale_start', models.DateTimeField(blank=True, help_text='When ticket sales start', null=True)),
                ('sale_end', models.DateTimeField(blank=True, help_text='When ticket sales end', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is ticket type available for sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.event')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, help_text='Unique ticket identifier', max_length=100, unique=True)),
                ('attendee_name', models.CharField(help_text='Name of the ticket holder', max_length=255)),
                ('attendee_email', models.EmailField(blank=True, help_text='Email of the ticket holder', max_length=254)),
                ('attendee_phone', models.CharField(blank=True, help_text='Phone of the ticket holder', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Price paid for this ticket', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='valid', help_text='Ticket status', max_length=20)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code for ticket validation', null=True, upload_to='tickets/qr_codes/%Y/%m/')),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='When ticket was checked in', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, help_text='Staff who checked in this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='Event this ticket is for', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.event')),
                ('order', models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.order')),
                ('ticket_type', models.ForeignKey(help_text='Type of ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the venue', max_length=255)),
                ('address', models.TextField(help_text='Full address of the venue')),
                ('city', models.CharField(help_text='City where venue is located', max_length=100)),
                ('country', models.CharField(default='Ghana', help_text='Country', max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity of the venue', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the venue')),
                ('image', models.ImageField(blank=True, help_text='Venue image', null=True, upload_to='venues/%Y/%m/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='idx_venue_city'), models.Index(fields=['country'], name='idx_venue_country')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Event venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.venue'),
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='User attended the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tickets.event')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Review',
                'verbose_name_plural': 'Event Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='idx_order_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='idx_order_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event'], name='idx_order_event'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='idx_payment_id'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='idx_payment_order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway'], name='idx_payment_gateway'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('event', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='idx_ticket_number'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order'], name='idx_ticket_order'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event'], name='idx_ticket_event'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='idx_ticket_status'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='idx_event_slug'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='idx_event_status'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='idx_event_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='idx_event_category'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='idx_event_organizer'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured'], name='idx_event_featured'),
        ),
    ]
