# Generated by Django 5.2.9 on 2025-12-14 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='Event organizer', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_profile',
            field=models.ForeignKey(blank=True, help_text='Payment profile for receiving event revenue', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='users.paymentprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(help_text='Event category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='event',
            field=models.ForeignKey(help_text='Event being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='user',
            field=models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(help_text='Event for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='event',
            field=models.ForeignKey(help_text='Event for this purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(help_text='User who made the purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.OneToOneField(help_text='Associated purchase', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tickets.purchase'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Staff who checked in this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(help_text='Event this ticket is for', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase',
            field=models.ForeignKey(help_text='Associated purchase', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.purchase'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(help_text='Type of ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ticket_type',
            field=models.ForeignKey(help_text='Ticket type purchased', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tickets.tickettype'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city'], name='idx_venue_city'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['country'], name='idx_venue_country'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='idx_event_slug_v2'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='idx_event_start_v2'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='idx_event_category_v2'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='idx_event_organizer_v2'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published'], name='idx_event_published'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue_city'], name='idx_event_city'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreview',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='idx_order_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='idx_order_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event'], name='idx_order_event'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='idx_payment_id_v2'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='idx_payment_reference'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status_v2'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('event', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_id'], name='idx_ticket_id_v2'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event'], name='idx_ticket_event_v2'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='idx_ticket_status_v2'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['purchase'], name='idx_ticket_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_id'], name='idx_purchase_id'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='idx_purchase_user'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='idx_purchase_status'),
        ),
    ]
