# Generated by Django 5.2.9 on 2025-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title (5-200 characters)', max_length=200),
        ),
    ]
