# Generated by Django 5.2.9 on 2026-01-04 21:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_contactmessage_newslettersubscription'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price paid for this ticket', max_digits=10),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('withdrawal_id', models.CharField(editable=False, help_text='Unique withdrawal identifier (WDR-XXXXXX)', max_length=50, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount requested by organizer', max_digits=10)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank transfer fee (deducted from requested amount)', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final amount to be transferred (requested_amount - transfer_fee)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', help_text='Withdrawal status', max_length=20)),
                ('transfer_code', models.CharField(blank=True, help_text='Paystack transfer code', max_length=255)),
                ('transfer_reference', models.CharField(blank=True, help_text='Paystack transfer reference', max_length=255)),
                ('transfer_response', models.JSONField(blank=True, default=dict, help_text='Full Paystack response')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When request was reviewed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this withdrawal')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When withdrawal was completed', null=True)),
                ('organizer', models.ForeignKey(help_text='Organizer requesting withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('payment_profile', models.ForeignKey(help_text='Bank account to receive funds', on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='users.paymentprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_sales_amount', models.DecimalField(decimal_places=2, help_text='Total from ticket sales (subtotal)', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform service fee deducted', max_digits=10)),
                ('organizer_earnings', models.DecimalField(decimal_places=2, help_text='Net earnings for organizer (ticket_sales - platform_fee)', max_digits=10)),
                ('is_withdrawn', models.BooleanField(default=False, help_text='Whether this revenue has been withdrawn')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available for Withdrawal'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='pending', help_text='Revenue status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_at', models.DateTimeField(blank=True, help_text='When revenue becomes available for withdrawal (e.g., 7 days after purchase)', null=True)),
                ('event', models.ForeignKey(help_text='Event that generated this revenue', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='tickets.event')),
                ('organizer', models.ForeignKey(help_text='Event organizer', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(help_text='Purchase that generated this revenue', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_record', to='tickets.purchase')),
                ('withdrawal', models.ForeignKey(blank=True, help_text='Withdrawal request this revenue is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='tickets.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Organizer Revenue',
                'verbose_name_plural': 'Organizer Revenue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['withdrawal_id'], name='idx_withdrawal_id'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['organizer'], name='idx_withdrawal_organizer'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='idx_withdrawal_status'),
        ),
        migrations.AddIndex(
            model_name='organizerrevenue',
            index=models.Index(fields=['organizer'], name='idx_revenue_organizer'),
        ),
        migrations.AddIndex(
            model_name='organizerrevenue',
            index=models.Index(fields=['event'], name='idx_revenue_event'),
        ),
        migrations.AddIndex(
            model_name='organizerrevenue',
            index=models.Index(fields=['status'], name='idx_revenue_status'),
        ),
        migrations.AddIndex(
            model_name='organizerrevenue',
            index=models.Index(fields=['is_withdrawn'], name='idx_revenue_withdrawn'),
        ),
    ]
