# Generated by Django 5.2.10 on 2026-01-24 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_ticket_price_withdrawalrequest_organizerrevenue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettype",
            name="max_purchase",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum tickets per purchase (leave empty for unlimited, max 1000)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
